version: '3.7'
services:
  rabbitmqserver:
    image: rabbitmq:3-management
    networks:
      - envoymesh
    ports:
      - "15672:15672" 
      - "5672:5672" 
  producer:
    image: cdi-rabbit-producer:latest
    networks:
      - envoymesh
    ports:
      - "8080:8080"
  consumer:
    image: cdi-rabbit-consumer:latest
    environment: 
      - DISABLE_SUSPENSION=true
    networks:
      - envoymesh
    ports:
      - "9090:9090"

networks:
  envoymesh: {}
