version: '3.7'
services:
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - pocnetwork
    ports:
      - "15672:15672" 
      - "5672:5672" 
  upstream:
    image: emmerson/upstream:mock
    networks:
      - pocnetwork
    ports:
      - "10003:10003"
  producer:
    image: emmerson/cdi-rabbit-producer:1.0.5
    networks:
      - pocnetwork
    ports:
      - "8080:8080"
      - "8888:8888"
      - "16000:16000"
  consumer:
    image: emmerson/cdi-rabbit-consumer:1.0.5
    environment: 
      - DISABLE_SUSPENSION=true
    networks:
      - pocnetwork
    ports:
      - "9090:9090"
      - "8888:8888"
      - "16000:16000" 
networks:
  pocnetwork: {}
