apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: cdi-error-handling-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cdi-error-handling
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metricName: camel3_noerrorroute_oneminuterate
      targetAverageValue: 100m
