apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cdi-error-handling-scaledobject
spec:
  scaleTargetRef:
    name: cdi-error-handling
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus.istio-system.svc.cluster.local:9090
      metricName: istio_requests_total
      threshold: '100'
      query: sum(rate(istio_requests_total{app="cdi-error-handling"}[1m]))
  - type: cron
    metadata:
      # Required
      timezone: Europe/London  # The acceptable values would be a value from the IANA Time Zone Database.
      start: 53 * * * *       # Every hour on the 30th minute
      end: 59 * * * *         # Every hour on the 45th minute
      desiredReplicas: "20"

#https://keda.sh/docs/2.2/concepts/scaling-deployments/